AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Creates an IAM Role that allows the specified management account to assume it for generating
  IAM Credential Reports in all member accounts.

Parameters:
  ManagementAccountId:
    Type: String
    Description: The AWS Account ID of the management account that can assume this role.

Resources:
  OrganizationCredentialReportRole:
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: "OrganizationCredentialReportRole"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              AWS: 
                - !Sub arn:aws:iam::${ManagementAccountId}:root
            Action: "sts:AssumeRole"
      Policies: 
        - PolicyName: "CredentialReportPolicy"
          PolicyDocument: 
            Version: "2012-10-17"
            Statement: 
              - Effect: "Allow"
                Action: 
                  - "iam:GenerateCredentialReport"
                  - "iam:GetCredentialReport"
                Resource: "*"

Outputs:
  RoleName:
    Description: "Name of the IAM Role created"
    Value: !Ref OrganizationCredentialReportRole
